theme: jekyll-theme-minimal
title: Edith Ackermann Archive
description: People are both world makers and beings-in-the-world &#58; they at once create their habitats, inhabit their creations, and become “inhabited” by them. —Ackermann, 2004, p. 26
